### ISSUE TITLE
Idea: make popout available for other pages

### ISSUE THREAD

**Issue by armandg** [rthaut/YouTubePopoutPlayer#115]
The video-tag is being more and more used these days. Wouldn't it then be possible to make this plugin functional for other pages as well?

**Comment by rthaut** [comment]
I am going to close this as "won't do" for this extension (though I understand the desire for such functionality), and here's the justification for that decision:

This extension relies on the fact that YouTube provides embeddable URLs for *most* videos, so we can open that URL in a small window.

However, that is not the case for all websites that host videos, and even the ones that do provide embeddable URLs have very different functionality/requirements for their embeds.

Since this extension is tightly coupled with YouTube's implementation of embedded videos, it would require a massive effort to individually add corresponding functionality for other hosts/providers.

---

As a side note, [Firefox 72.0](https://www.mozilla.org/en-US/firefox/72.0/releasenotes/) added [native support for picture-in-picture](https://support.mozilla.org/en-US/kb/about-picture-picture-firefox) that works with all `<video>`s, so I recommend people looking for a solution that is not specific to YouTube make use of that feature.
