### ISSUE TITLE
Addon stops working after Mozilla restart

### ISSUE THREAD

**Issue by Talismancer** [rthaut/YouTubePopoutPlayer#14]
Hi...after a restart of Firefox the addon stopped showing either the arrow icon or the entry in the video drop-down menu. So far I've tried toggling disable/enable (doesn't work) and removing & re-installing (which does work but only as a once off).

This is a brilliant addon! I added a mini Autohotkey script to hold the window always on top.
SendMode Input
^SPACE::  Winset, Alwaysontop, , A
Cheers....Justin

**Comment by Talismancer** [comment]
I have no idea what has changed...but it now works perfectly. Cheers for a great addon!

**Comment by rthaut** [comment]
@Talismancer thanks for the report and the follow-up. I was never able to reproduce the problem you described -- although I only tried on 3 machines, all running the same OS, so that is certainly not extensive troubleshooting.

I'm going to close this issue for now, but if you (or anyone else) encounters this problem, please add a report here (and, if possible, include your Operating System details, Firefox version details, etc.).
