### ISSUE TITLE
Automatically popout on page click and use same player

### ISSUE THREAD

**Issue by cregham** [rthaut/YouTubePopoutPlayer#375]
No idea if this is possible. 

Setting for 'always open video urls in popout'. Skip the need to open the videos page. If i'm on my homepage or search results, as soon as I click a thumbnail or link the popout player is opened.

Which leads me onto the second requests. If the popout player is already open. Is it possible to use the same window. Everytime I click a popout button it opens a new window.

**Comment by rthaut** [comment]
The first request is already partially available right now: there's a right-click menu option on any valid YouTube video link that will open the linked video in the PopOut Player.

It might be possible to "intercept" the normal click to open the PopOut Player instead of going to the video page, though I would need to look into it some more. I am certain that it would go against best practices and common conventions. so it would at the very least need an aggressive warning before turning it on. :-)

As for re-using an existing window, that seems like a great idea for an enhancement and should definitely be doable.

**Comment by KamonegiX** [comment]
I recently started using this extension too after a few years of no updates my previous extension used for (mostly) the popup-player finally broke (Iridium).

So far I am pretty happy with the extension but would also like to second that "use previous window for new popup player requests" - the extension always opening a new window is a bit of a problem but not really a deal-breaker.

How Iridium got around the "not opening the video to popup" was adding a "button" to every thumbnail on YouTube and I think that was a genius way to solve that issue. The right-click menu is ok for me but I REALLY would love an Icon on the thumbnails again.

See screenshot:
![W4Wv1VbXVK](https://user-images.githubusercontent.com/103597356/163238312-bb3a1fc0-39cb-4c06-9e84-dc8169f56b4b.png)

**Comment by rthaut** [comment]
I split this into 2 tickets:
- #379 
- #380 

Reusing the existing popout window is available as a new option that can be enabled in v4.2.0, which is pending review before going live (hopefully in the next 24 hours).

For opening the popout with a single primary/left click, I am still looking into a good way to implement this.
